# -*- coding: utf-8 -*-
"""作業四.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Ccmdk1wGdhPACGBXe8W6Vq1VXQ6lYre

1.
"""

import numpy as np

a= np.array([[2,3,5],[5,7,8]])
b= np.array([[1,2],[3,10],[2,6]])
print(a.dot(b))

"""2."""

import numpy as np

A=np.array([32,57,89,82,98,57,88,56,93,91])
B=np.array([88,93,20,70,56,83,92,100,80,97])
C=np.array([82,75,83,95,96,90,77,82,90,88])

thisdict={"A":A,"B":B,"C":C}

for key in thisdict.keys():
  print(key,"class:","總和:",np.sum(thisdict[key]),"最大:",np.max(thisdict[key]))