# -*- coding: utf-8 -*-
"""作業一.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o2QDyZrRTMyQXqUw8s0fl-0oK0yZg1FH

1.
"""

try:
  x = int(input("被除數"))
  y = int(input("除數"))
  print("{:.2f}".format(x/y))
except:
  print("數字格式錯誤")

"""2."""

x=int(input("x:"))
if x%6==0:
  print ("x為6的倍數")
elif x%3==0:
  print("x為3的倍數")
elif x%2==0:
  print("x為2的倍數")

"""3."""

x=int(input("秒數"))
s= int(x%60)
m= int((x%3600-x%60)/60)
h= int(x//3600)
print (h,":",m,":",s)

"""4."""

i= int(input("請輸入偶數"))
if i%2==0:
  while i>0:
    print(i-1)
    i-=2
else:
  print("輸入錯誤，",i,"不為偶數")