# -*- coding: utf-8 -*-
"""作業二.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p2vaiYo5eV8wExkw6wZIeTeTNVkm-GgV

1.
"""

n=int(input("請輸入數字"))
ans=0
print(1,end="")
for i in range(2,n+1,1):
  ans=ans+i
  ans1=ans+1
  print("+",i,end="")
print("=",ans1)

"""2."""

s=input("請輸入一串字串")
s=s.split()

m=int(input("請輸入數字"))
int_i = [int(i) for i in s if int(i)>=m]
print(int_i)

"""3."""

s=input("請輸入一串字串")
s=s.split()

int_i = [int(i) for i in s if int(i)%2==0]
print(sum(int_i))

"""4."""

s=input("主字串")
n=input("子字串")

count=s.count(n)
print("出現次數",count)